### ISSUE TITLE
Release version 2.0.11 to pypi

### ISSUE THREAD

**Issue by Erik-vdg** [memiiso/pyliquibase#29]
Currently the most recent version available on pypi is 2.0.7, whereas this project is currently on version 2.0.11. I'd like to be able to use the newest version of this project at my work easily by installing from pypi.

**Comment by ismailsimsek** [comment]
Thank you @Erik-vdg  released now

**Comment by Erik-vdg** [comment]
Thank you kindly @ismailsimsek for the speedy resolution!
