### ISSUE TITLE
Release new version on PyPI

### ISSUE THREAD

**Issue by ovaluiskyi** [memiiso/pyliquibase#45]
Pyliqubase added a lot of new features, since 2.0.11, like
- Added new commands: update_to_tag, changelog_sync, changelog_sync_to_tag, clear_checksums, release_locks
- Add a method for downloading additional jar libraries
- Add option to set jdbcDriversDir
- Updated liquibase to 4.2.1
- Support Python 3.11 (via pyjnius 1.5.0)

Is it possible to release a new version to PyPI?

**Comment by ismailsimsek** [comment]
@ovaluiskyi just released i, its available on pypi now

**Comment by ovaluiskyi** [comment]
Thank you!
