### ISSUE TITLE
Failed to download liquibase-snowflake

### ISSUE THREAD

**Issue by ovaluiskyi** [memiiso/pyliquibase#46]
Pyliquibase 2.0.12 throws an error on any command
```
Downloading java lib: https://github.com/liquibase/liquibase-snowflake/releases/download/v4.21.1/liquibase-snowflake-4.21.1.jar to /Home/Documents/Projects/my_project/venv/lib/python3.11/site-packages/pyliquibase/liquibase-4.21.1/lib/liquibase-snowflake-4.21.1.jar
Failed to download https://github.com/liquibase/liquibase-snowflake/releases/download/v4.21.1/liquibase-snowflake-4.21.1.jar
Failed to download Liquibase extension: liquibase-snowflake-4.21.1
```

It happens because snowflake is now supported directly by the liquibase project.

I have also two questions
1) Why pyliquibase downloads `liquibase-bigquery` and `liquibase-redshift` by default? They can be downloaded via 'download_additional_java_library' method only if needed
2) What is the purpose of `jdbc-drivers` folder? This folder adds 65 MB of extra space to each docker image

**Comment by ismailsimsek** [comment]
it should be just a log message. i cannot reproduce exception locally. `warning` could better log level for that. 

it is coming from initial earlier code. agree its best remove them and leave it to enduser to download the libs. 

`jdbc-drivers` is used to keep jdbc driver libaries. it is also coming with earlier setup. this libraries too should be removed, and be left to enduser to download. i believe its adding Bigquery and other jdbc drivers. so far i didn't delete them to keep backward compatible.

feel free to send MR
