### ISSUE TITLE
Upgrading Liquibase version breaks the application

### ISSUE THREAD

**Issue by gamaleonardo** [memiiso/pyliquibase#52]
Hi!

I saw that you increased the version for Liquibase in your project. But between its versions there was some structural changes which were not adapted in pyliquibase code. For example, the file "liquibase.jar" does not exist anymore.

Some changes in \_\_init__.py file must be made. If you want I can contribute!
And thanks for this library, it will save my tests :)

**Comment by ismailsimsek** [comment]
@gamaleonardo thank you for reporting it, of course please feel free to open PR.

**Comment by ismailsimsek** [comment]
Closed by #54
