### ISSUE TITLE
"Unable to find the class liquibase/integration/commandline/LiquibaseCommandLine"

### ISSUE THREAD

**Issue by gamaleonardo** [memiiso/pyliquibase#53]
Hi!

For the moment I'm using liquibase 4.11.0, the previous version matching with the current code. But I'm getting this error:

"jnius.JavaException: Unable to find the class liquibase/integration/commandline/LiquibaseCommandLine"

Would you know how to solve it?
Thanks!

**Comment by ismailsimsek** [comment]
for version 4.11.0 is the file `liquibase.jar` imported as classpath? and available? 

```
jnius_config.add_classpath(*LIQUIBASE_CLASSPATH)
```

**Comment by gamaleonardo** [comment]
Hi 
I found the issue, I will push it, but I'm not able to create a branch. Could you give me the rights please?

**Comment by ismailsimsek** [comment]
@gamaleonardo you need to fork the project, then create new branch and then PR 

please see https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request?tool=webui

**Comment by gamaleonardo** [comment]
No worries I'll do it. Thanks

**Comment by gamaleonardo** [comment]
Closed by https://github.com/memiiso/pyliquibase/pull/54

**Comment by gamaleonardo** [comment]
Closed by https://github.com/memiiso/pyliquibase/pull/54
