### ISSUE TITLE
Failed to download jar files on run time

### ISSUE THREAD

**Issue by mmadhuhasa** [memiiso/pyliquibase#65]
Error occurs after this line,
Pyliquibase(defaultsFile="changelogs/liquibase.properties", liquibaseDir="/opt/liquibase")
liquibase.status()

Please update the code to download jar files from new url in liquibase repository,

Below URL are not available, error shows like
Error - Failed to download
https://github.com/liquibase/liquibase-bigquery/releases/download/liquibase-bigquery-4.21.1/liquibase-bigquery-4.21.1.jar
Error - Failed to download
https://github.com/liquibase/liquibase-redshift/releases/download/liquibase-redshift-4.21.1/liquibase-redshift-4.21.1.jar

But, Actual working URL  is,
https://github.com/liquibase/liquibase-bigquery/releases/download/v4.21.1/liquibase-bigquery-4.21.1.jar
https://github.com/liquibase/liquibase-redshift/releases/download/v4.21.1/liquibase-redshift-4.21.1.jar

**Comment by mmadhuhasa** [comment]
Please respond for this issue

**Comment by pidanou** [comment]
@mmadhuhasa https://github.com/memiiso/pyliquibase/pull/67 maybe it will fix the issue

**Comment by mmadhuhasa** [comment]
Above issue is fixed and push in master branch, thanks for support
And one confirmation is that,
 where dependent jar files are downloaded before connecting to database, 
 Is that right ?
