### ISSUE TITLE
consider to upgrade for latest pyjnius 1.6.0 package

### ISSUE THREAD

**Issue by mmadhuhasa** [memiiso/pyliquibase#66]
`ERROR: Cannot install pyjnius==1.6.0 and pyliquibase 2.0.13 because these package versions have conflicting dependencies.

The conflict is caused by:

The user requested pyjnius==1.6.0 pyliquibase 2.0.13 depends on pyjnius==1.5.0`

Above issue is coming when we try to upgrade pyjnius package.
We need latest package of pyjnius, where some issues are resolved, on specifically the issue is https://github.com/kivy/pyjnius/issues/674

**Comment by pidanou** [comment]
Same issue here when I am trying to build a Docker image.
On my machine it works fine though.

**Comment by pidanou** [comment]
I did a PR for a fix: https://github.com/memiiso/pyliquibase/pull/67 
Not sure if it's the proper way. It looks like it works on my side.
In the meantime @mmadhuhasa , you can check directly on my forked repo
