### ISSUE TITLE
When can we expect next version release officially

### ISSUE THREAD

**Issue by mmadhuhasa** [memiiso/pyliquibase#69]

**Comment by pidanou** [comment]
If you're using pip, you can directly install from this github source. For example in your requirements.txt:
`git+https://github.com/memiiso/pyliquibase.git`

**Comment by mmadhuhasa** [comment]
Yes currently we are using the above solution, but we're moving our code changes to production. 
It's urgent, so when can we expect the release

**Comment by mmadhuhasa** [comment]
Please release next version

**Comment by ismailsimsek** [comment]
released 2.1.0 

- https://github.com/memiiso/pyliquibase/releases/tag/2.1.0
- https://pypi.org/project/pyliquibase/2.1.0/
